# Generated by Django 5.1.6 on 2025-02-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.CharField(max_length=1023),
        ),
    ]
